### ISSUE TITLE
Error with Restore

### ISSUE THREAD

**Issue by fillon** [clintmod/macprefs#1]
stephane@mac:~$ sudo macprefs restore

Restoring system preferences...
Restoring: /Library/Preferences/SystemConfiguration/com.apple.PowerManagement from /Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist
Error Info:
error code = 1
cmd ['defaults', 'import', '/Library/Preferences/SystemConfiguration/com.apple.PowerManagement', '/Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist']
error message: 2017-11-22 06:06:56.029 defaults[57120:244331] Could not read data from /Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist

Traceback (most recent call last):
  File "/usr/local/bin/macprefs", line 55, in <module>
    main()
  File "/usr/local/bin/macprefs", line 51, in main
    invoke_func(args)
  File "/usr/local/bin/macprefs", line 32, in invoke_func
    args.func()
  File "/usr/local/bin/macprefs", line 23, in restore
    system_preferences.restore()
  File "/usr/local/Cellar/macprefs/1.0.15/bin/system_preferences.py", line 46, in restore
    power_management_restore_path])
  File "/usr/local/Cellar/macprefs/1.0.15/bin/utils.py", line 14, in execute_shell
    cwd=cwd, stderr=STDOUT).strip()
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['defaults', 'import', '/Library/Preferences/SystemConfiguration/com.apple.PowerManagement', '/Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist']' returned non-zero exit status 1

**Comment by clintmod** [comment]
What version are you using? `macprefs --version`

**Comment by clintmod** [comment]
I would try with the latest version I just uploaded this morning... I fixed a bunch permission things. And then just run the restore without sudo `macprefs restore`. It will prompt you for a password to sudo when it needs too.

**Comment by clintmod** [comment]
Also I would check that you don't have case conflicts by running `sudo ls -la /private/var/root/Library/Preferences | grep -i case`

**Comment by clintmod** [comment]
Went through the git history this was fixed in [v1.0.17](https://github.com/clintmod/macprefs/releases/tag/v1.0.17) run `brew upgrade macprefs` and then `macprefs restore`

**Comment by fillon** [comment]
Thanks :)
I was using 1.0.15, upgraded to 1.0.17 no more error message
