### ISSUE TITLE
cannot create backup

### ISSUE THREAD

**Issue by michael-bakker** [clintmod/macprefs#2]
Hello,

I've just installed macprefs but I'm unable to create a backup because the folder

/Library/Application Support/com.apple.sharedfilelist

doesn't exist on my machine.

I just (re)installed from an existing TimeMachine backup a few days ago and I'm running macOS Sierra (10.12.6).

Attached I'm sending you the output when running "macprefs backup".

[log.txt](https://github.com/clintmod/macprefs/files/1510159/log.txt)

**Comment by clintmod** [comment]
Checking this out now… I'll just print a warning if the folder is missing.

**Comment by clintmod** [comment]
fixed in version 1.0.23

**Comment by michael-bakker** [comment]
Wow. That was pretty fast. Working as suggested now. Thanks for your tool!
