### ISSUE TITLE
install via homebrew: env: python: No such file or directory

### ISSUE THREAD

**Issue by avelino** [clintmod/macprefs#20]
```
~ ❯❯❯ macprefs backup
env: python: No such file or directory
```

**macOS:** 13.1 (22C65)
**Processor:** Intel Core i9
**install command:** `brew install clintmod/formulas/macprefs`

**Comment by tillydray** [comment]
@avelino this might be related to https://github.com/clintmod/macprefs/issues/9. Summary is that you need to use Python 2, _not_ 3
