### ISSUE TITLE
Backup ~/Library/Containers for App Store apps

### ISSUE THREAD

**Issue by clintmod** [clintmod/macprefs#3]
I'd like to backup the ~/Library/Containers for app store application preferences but it also contains a bunch of other files and symlinks to directories. Symlinks don't play well with dropbox as it likes to follow them and back up a bunch of unintended stuff. This was requested by @michael-bakker

**Comment by clintmod** [comment]
Adding original email:

Hi,

thanks once again for your fast bugfix :)

I ran "macprefs backup" but I'm missing at least one of my applications that are shown in "defaults domains". Its domain name is:

com.catpigstudios.Radium3

Please do not wonder about its domain name ;) Radium is a radio application software.

Although I can write and understand a little bit of python I was unable to see why it does not generate any backup in this case.

When looking for corresponding "configuration files" I found

~/Library/Containers/com.catpigstudios.Radium3

that holds for example

~/Library/Containers/com.catpigstudios.Radium3/Data/Library/Preferences/com.catpigstudios.Radium3.plist

Is this special case with Library/Containers maybe not handled so far and thats why its missing? This application also stores some of its configurations in "defaults * com.catpigstudios.Radium3" that I'm also looking for.

Thumbs up for your nice work so far!

Greetings from germany.

**Comment by michael-bakker** [comment]
![giphy](https://user-images.githubusercontent.com/24475227/33381600-c7a5c8a6-d51e-11e7-8c15-efafa6b260c1.gif)

Looks great for me! Thanks once again 👍
